"""initial migration

Revision ID: c5d4be450ad8
Revises: 
Create Date: 2025-04-14 08:39:53.838722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d4be450ad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('st_id', sa.Integer(), nullable=False),
    sa.Column('st_name', sa.String(length=20), nullable=False),
    sa.Column('st_email', sa.String(length=50), nullable=False),
    sa.Column('st_dob', sa.Date(), nullable=False),
    sa.Column('st_phone', sa.String(length=20), nullable=True),
    sa.Column('st_current_inst', sa.String(length=30), nullable=False),
    sa.Column('st_password', sa.String(length=255), nullable=False),
    sa.Column('st_date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('st_id'),
    sa.UniqueConstraint('st_email')
    )
    op.create_table('subject',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('teacher',
    sa.Column('ta_id', sa.Integer(), nullable=False),
    sa.Column('ta_name', sa.String(length=20), nullable=False),
    sa.Column('ta_email', sa.String(length=50), nullable=False),
    sa.Column('ta_dob', sa.Date(), nullable=False),
    sa.Column('ta_phone', sa.String(length=20), nullable=True),
    sa.Column('ta_init', sa.String(length=15), nullable=False),
    sa.Column('ta_password', sa.String(length=255), nullable=False),
    sa.Column('ta_date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ta_id'),
    sa.UniqueConstraint('ta_email'),
    sa.UniqueConstraint('ta_init')
    )
    op.create_table('quiz',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('no_of_q', sa.Integer(), nullable=False),
    sa.Column('belongs_to', sa.Integer(), nullable=False),
    sa.Column('set_by', sa.Integer(), nullable=False),
    sa.Column('highest_mark', sa.Integer(), nullable=True),
    sa.Column('total_mark', sa.Integer(), nullable=False),
    sa.Column('expired', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['belongs_to'], ['subject.sid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by'], ['teacher.ta_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_table('question',
    sa.Column('quid', sa.Integer(), nullable=False),
    sa.Column('belongs_to', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['belongs_to'], ['quiz.qid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('quiz')
    op.drop_table('teacher')
    op.drop_table('subject')
    op.drop_table('student')
    # ### end Alembic commands ###
